# Generated by Django 6.0.3 on 2026-03-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégories'},
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('once', 'Once')], default='once', max_length=10, null=True, verbose_name='Récurence'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la dépense'),
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='income',
            name='frequency',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('once', 'Once')], default='once', max_length=10, null=True, verbose_name='Récurence'),
        ),
        migrations.AlterField(
            model_name='income',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la dépense'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='frequency',
            field=models.CharField(blank=True, choices=[('yearly', 'Yearly'), ('monthly', 'Monthly'), ('weekly', 'Weekly'), ('daily', 'Daily'), ('once', 'Once')], default='once', max_length=10, null=True, verbose_name='Récurence'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom de la dépense'),
        ),
    ]
