# Generated by Django 6.0.3 on 2026-03-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_savingsaccount_savings_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(blank=True, choices=[('annuel', 'Annuel'), ('mensuel', 'Mensuel'), ('hebdo', 'Hebdomadaire'), ('journalier', 'Journalière'), ('unique', 'Unique')], default='unique', max_length=10, null=True, verbose_name='Récurence'),
        ),
        migrations.AlterField(
            model_name='income',
            name='frequency',
            field=models.CharField(blank=True, choices=[('annuel', 'Annuel'), ('mensuel', 'Mensuel'), ('hebdo', 'Hebdomadaire'), ('journalier', 'Journalière'), ('unique', 'Unique')], default='unique', max_length=10, null=True, verbose_name='Récurence'),
        ),
        migrations.AlterField(
            model_name='savings',
            name='frequency',
            field=models.CharField(blank=True, choices=[('annuel', 'Annuel'), ('mensuel', 'Mensuel'), ('hebdo', 'Hebdomadaire'), ('journalier', 'Journalière'), ('unique', 'Unique')], default='unique', max_length=10, null=True, verbose_name='Récurence'),
        ),
    ]
