# Generated by Django 6.0.3

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_alter_expense_frequency_alter_income_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant prévu')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_expenses', to='main_app.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dépense prévisionnelle',
                'ordering': ['category__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='plannedexpense',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'year', 'month'), name='unique_planned_expense_per_category_month'),
        ),
    ]
