# Generated by Django 6.0.3 on 2026-09-30 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_category_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Dépense'},
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_occurrences', to='main_app.expense', verbose_name="Dépense récurrente d'origine"),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('recurring_from__isnull', False)), fields=('recurring_from', 'date'), name='unique_expense_recurring_date'),
        ),
    ]
