# Generated by Django 6.0.3 on 2026-10-02 11:52

from django.conf import settings
from django.db import migrations, models


def copy_latest_month_into_template(apps, schema_editor):
    """Transforme le dernier montant de chaque catégorie en jeu habituel."""
    PlannedExpense = apps.get_model('main_app', 'PlannedExpense')
    pairs = (
        PlannedExpense.objects.filter(year__isnull=False)
        .values_list('user_id', 'category_id')
        .distinct()
    )
    for user_id, category_id in pairs:
        rows = list(
            PlannedExpense.objects.filter(
                user_id=user_id,
                category_id=category_id,
                year__isnull=False,
            ).order_by('-year', '-month', '-pk')
        )
        if not rows:
            continue
        already = PlannedExpense.objects.filter(
            user_id=user_id,
            category_id=category_id,
            year__isnull=True,
            month__isnull=True,
        ).exists()
        if already:
            continue
        latest = rows[0]
        PlannedExpense.objects.create(
            user_id=user_id,
            category_id=category_id,
            amount=latest.amount,
            year=None,
            month=None,
        )
        for row in rows:
            if row.amount == latest.amount:
                row.delete()


def drop_templates(apps, schema_editor):
    """Retire les montants habituels pour pouvoir revenir au schéma précédent."""
    PlannedExpense = apps.get_model('main_app', 'PlannedExpense')
    PlannedExpense.objects.filter(year__isnull=True, month__isnull=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_expense_recurring_from'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plannedexpense',
            name='unique_planned_expense_per_category_month',
        ),
        migrations.AlterField(
            model_name='plannedexpense',
            name='month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plannedexpense',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='plannedexpense',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', True)), fields=('user', 'category'), name='unique_planned_template_per_category'),
        ),
        migrations.AddConstraint(
            model_name='plannedexpense',
            constraint=models.UniqueConstraint(condition=models.Q(('year__isnull', False)), fields=('user', 'category', 'year', 'month'), name='unique_planned_expense_per_category_month'),
        ),
        migrations.AddConstraint(
            model_name='plannedexpense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('month__isnull', True), ('year__isnull', True)), models.Q(('month__isnull', False), ('year__isnull', False)), _connector='OR'), name='planned_expense_template_or_month'),
        ),
        migrations.RunPython(copy_latest_month_into_template, drop_templates),
    ]
