# Generated by Django 6.0.3 on 2026-10-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_planned_expense_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedexpense',
            name='apply_forward',
            field=models.BooleanField(default=False, verbose_name='Appliquer aux mois suivants'),
        ),
    ]
